import { User } from '../models/user.model';
import { Training } from '../models/training.model';
import { TrainingAssignment } from '../models/assignment.model';

export const MOCK_USERS: User[] = [
  {
    id: 'user-001',
    email: 'admin@company.com',
    firstName: 'Admin',
    lastName: 'Thompson',
    role: 'admin',
    department: 'Engineering',
    avatarUrl: 'https://ui-avatars.com/api/?name=Admin+Thompson&background=random',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user-002',
    email: 'sarah.admin@company.com',
    firstName: 'Sarah',
    lastName: 'Chen',
    role: 'admin',
    department: 'Human Resources',
    avatarUrl: 'https://ui-avatars.com/api/?name=Sarah+Chen&background=random',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'user-003',
    email: 'john@company.com',
    firstName: 'John',
    lastName: 'Smith',
    role: 'employee',
    department: 'Engineering',
    avatarUrl: 'https://ui-avatars.com/api/?name=John+Smith&background=random',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'user-004',
    email: 'jane@company.com',
    firstName: 'Jane',
    lastName: 'Doe',
    role: 'employee',
    department: 'Marketing',
    avatarUrl: 'https://ui-avatars.com/api/?name=Jane+Doe&background=random',
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 'user-005',
    email: 'bob@company.com',
    firstName: 'Bob',
    lastName: 'Wilson',
    role: 'employee',
    department: 'Finance',
    avatarUrl: 'https://ui-avatars.com/api/?name=Bob+Wilson&background=random',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'user-006',
    email: 'alice@company.com',
    firstName: 'Alice',
    lastName: 'Brown',
    role: 'employee',
    department: 'Engineering',
    avatarUrl: 'https://ui-avatars.com/api/?name=Alice+Brown&background=random',
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'user-007',
    email: 'mike@company.com',
    firstName: 'Mike',
    lastName: 'Davis',
    role: 'employee',
    department: 'Marketing',
    avatarUrl: 'https://ui-avatars.com/api/?name=Mike+Davis&background=random',
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'user-008',
    email: 'emma@company.com',
    firstName: 'Emma',
    lastName: 'Taylor',
    role: 'employee',
    department: 'Human Resources',
    avatarUrl: 'https://ui-avatars.com/api/?name=Emma+Taylor&background=random',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'user-009',
    email: 'david@company.com',
    firstName: 'David',
    lastName: 'Lee',
    role: 'employee',
    department: 'Finance',
    avatarUrl: 'https://ui-avatars.com/api/?name=David+Lee&background=random',
    createdAt: new Date('2024-03-15'),
  },
  {
    id: 'user-010',
    email: 'lisa@company.com',
    firstName: 'Lisa',
    lastName: 'Anderson',
    role: 'employee',
    department: 'Engineering',
    avatarUrl: 'https://ui-avatars.com/api/?name=Lisa+Anderson&background=random',
    createdAt: new Date('2024-03-20'),
  },
];

export const MOCK_TRAININGS: Training[] = [
  {
    id: 'train-001',
    title: 'GDPR Data Protection',
    description:
      'Comprehensive training on General Data Protection Regulation requirements, data handling best practices, and privacy obligations for all employees.',
    category: 'compliance',
    status: 'active',
    durationMinutes: 90,
    passingScore: 80,
    isMandatory: true,
    expiresAfterDays: 365,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'train-002',
    title: 'Workplace Safety Fundamentals',
    description:
      'Core workplace safety principles including hazard identification, ergonomic practices, and reporting procedures to maintain a safe work environment.',
    category: 'safety',
    status: 'active',
    durationMinutes: 60,
    passingScore: 70,
    isMandatory: true,
    expiresAfterDays: 365,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'train-003',
    title: 'Information Security Awareness',
    description:
      'Essential training on cybersecurity threats, phishing prevention, password management, and secure handling of sensitive company information.',
    category: 'compliance',
    status: 'active',
    durationMinutes: 45,
    passingScore: 85,
    isMandatory: true,
    expiresAfterDays: 180,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'train-004',
    title: 'Anti-Harassment Policy',
    description:
      'Mandatory training covering workplace harassment prevention, recognizing inappropriate behavior, reporting channels, and company policies on discrimination.',
    category: 'compliance',
    status: 'active',
    durationMinutes: 30,
    passingScore: 75,
    isMandatory: true,
    expiresAfterDays: 365,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'train-005',
    title: 'Fire Safety & Evacuation',
    description:
      'Training on fire prevention, emergency evacuation procedures, fire extinguisher usage, and assembly point protocols for all office locations.',
    category: 'safety',
    status: 'active',
    durationMinutes: 30,
    passingScore: 80,
    isMandatory: true,
    expiresAfterDays: 365,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'train-006',
    title: 'Advanced TypeScript',
    description:
      'Deep dive into TypeScript advanced features including generics, conditional types, mapped types, decorators, and design patterns for scalable applications.',
    category: 'technical',
    status: 'active',
    durationMinutes: 120,
    passingScore: 70,
    isMandatory: false,
    expiresAfterDays: null,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-08-12'),
  },
  {
    id: 'train-007',
    title: 'Leadership Communication',
    description:
      'Develop effective communication strategies for team leadership, including giving feedback, facilitating meetings, and managing difficult conversations.',
    category: 'soft-skills',
    status: 'active',
    durationMinutes: 90,
    passingScore: 60,
    isMandatory: false,
    expiresAfterDays: null,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-07-20'),
  },
  {
    id: 'train-008',
    title: 'AWS Cloud Practitioner',
    description:
      'Foundational AWS cloud concepts covering core services, security, architecture, pricing, and support to prepare for the Cloud Practitioner certification.',
    category: 'certification',
    status: 'active',
    durationMinutes: 180,
    passingScore: 80,
    isMandatory: false,
    expiresAfterDays: 730,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'train-009',
    title: 'First Aid Training',
    description:
      'Practical first aid skills including CPR, wound treatment, shock management, and emergency response procedures for workplace incidents.',
    category: 'safety',
    status: 'active',
    durationMinutes: 60,
    passingScore: 75,
    isMandatory: true,
    expiresAfterDays: 365,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'train-010',
    title: 'Agile Project Management',
    description:
      'Introduction to Agile methodologies including Scrum, Kanban, sprint planning, retrospectives, and effective backlog management for cross-functional teams.',
    category: 'soft-skills',
    status: 'active',
    durationMinutes: 90,
    passingScore: 65,
    isMandatory: false,
    expiresAfterDays: null,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-08-30'),
  },
];

export const MOCK_ASSIGNMENTS: TrainingAssignment[] = [
  // John Smith (user-003) - Engineering - 5 assignments
  {
    id: 'assign-001',
    trainingId: 'train-001',
    employeeId: 'user-003',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-06-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-20'),
    score: 92,
    attempts: 1,
  },
  {
    id: 'assign-002',
    trainingId: 'train-003',
    employeeId: 'user-003',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-07-01'),
    dueDate: new Date('2024-08-01'),
    completedDate: new Date('2024-07-15'),
    score: 88,
    attempts: 1,
  },
  {
    id: 'assign-003',
    trainingId: 'train-006',
    employeeId: 'user-003',
    assignedById: 'user-001',
    status: 'in-progress',
    assignedDate: new Date('2024-09-15'),
    dueDate: new Date('2024-11-15'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-004',
    trainingId: 'train-005',
    employeeId: 'user-003',
    assignedById: 'user-002',
    status: 'not-started',
    assignedDate: new Date('2024-10-01'),
    dueDate: new Date('2024-11-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-005',
    trainingId: 'train-009',
    employeeId: 'user-003',
    assignedById: 'user-002',
    status: 'overdue',
    assignedDate: new Date('2024-08-01'),
    dueDate: new Date('2024-09-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // Jane Doe (user-004) - Marketing - 4 assignments
  {
    id: 'assign-006',
    trainingId: 'train-001',
    employeeId: 'user-004',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-06-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-25'),
    score: 85,
    attempts: 2,
  },
  {
    id: 'assign-007',
    trainingId: 'train-004',
    employeeId: 'user-004',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-05-15'),
    dueDate: new Date('2024-06-15'),
    completedDate: new Date('2024-06-10'),
    score: 78,
    attempts: 1,
  },
  {
    id: 'assign-008',
    trainingId: 'train-007',
    employeeId: 'user-004',
    assignedById: 'user-001',
    status: 'in-progress',
    assignedDate: new Date('2024-09-20'),
    dueDate: new Date('2024-11-20'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-009',
    trainingId: 'train-002',
    employeeId: 'user-004',
    assignedById: 'user-002',
    status: 'overdue',
    assignedDate: new Date('2024-07-15'),
    dueDate: new Date('2024-08-15'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // Bob Wilson (user-005) - Finance - 5 assignments
  {
    id: 'assign-010',
    trainingId: 'train-001',
    employeeId: 'user-005',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-06-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-28'),
    score: 81,
    attempts: 2,
  },
  {
    id: 'assign-011',
    trainingId: 'train-003',
    employeeId: 'user-005',
    assignedById: 'user-001',
    status: 'expired',
    assignedDate: new Date('2024-03-01'),
    dueDate: new Date('2024-04-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-012',
    trainingId: 'train-004',
    employeeId: 'user-005',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-05-01'),
    dueDate: new Date('2024-06-01'),
    completedDate: new Date('2024-05-20'),
    score: 90,
    attempts: 1,
  },
  {
    id: 'assign-013',
    trainingId: 'train-005',
    employeeId: 'user-005',
    assignedById: 'user-002',
    status: 'not-started',
    assignedDate: new Date('2024-10-05'),
    dueDate: new Date('2024-11-05'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-014',
    trainingId: 'train-010',
    employeeId: 'user-005',
    assignedById: 'user-001',
    status: 'in-progress',
    assignedDate: new Date('2024-09-10'),
    dueDate: new Date('2024-11-10'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // Alice Brown (user-006) - Engineering - 5 assignments
  {
    id: 'assign-015',
    trainingId: 'train-001',
    employeeId: 'user-006',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-06-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-18'),
    score: 95,
    attempts: 1,
  },
  {
    id: 'assign-016',
    trainingId: 'train-003',
    employeeId: 'user-006',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-07-01'),
    dueDate: new Date('2024-08-01'),
    completedDate: new Date('2024-07-22'),
    score: 91,
    attempts: 1,
  },
  {
    id: 'assign-017',
    trainingId: 'train-006',
    employeeId: 'user-006',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-05-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-15'),
    score: 87,
    attempts: 1,
  },
  {
    id: 'assign-018',
    trainingId: 'train-008',
    employeeId: 'user-006',
    assignedById: 'user-001',
    status: 'in-progress',
    assignedDate: new Date('2024-09-01'),
    dueDate: new Date('2024-12-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-019',
    trainingId: 'train-009',
    employeeId: 'user-006',
    assignedById: 'user-002',
    status: 'not-started',
    assignedDate: new Date('2024-10-10'),
    dueDate: new Date('2024-11-10'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // Mike Davis (user-007) - Marketing - 4 assignments
  {
    id: 'assign-020',
    trainingId: 'train-001',
    employeeId: 'user-007',
    assignedById: 'user-002',
    status: 'overdue',
    assignedDate: new Date('2024-07-01'),
    dueDate: new Date('2024-08-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-021',
    trainingId: 'train-004',
    employeeId: 'user-007',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-05-15'),
    dueDate: new Date('2024-06-15'),
    completedDate: new Date('2024-06-12'),
    score: 76,
    attempts: 2,
  },
  {
    id: 'assign-022',
    trainingId: 'train-007',
    employeeId: 'user-007',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-04-01'),
    dueDate: new Date('2024-06-01'),
    completedDate: new Date('2024-05-28'),
    score: 72,
    attempts: 1,
  },
  {
    id: 'assign-023',
    trainingId: 'train-002',
    employeeId: 'user-007',
    assignedById: 'user-002',
    status: 'not-started',
    assignedDate: new Date('2024-10-01'),
    dueDate: new Date('2024-11-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // Emma Taylor (user-008) - Human Resources - 5 assignments
  {
    id: 'assign-024',
    trainingId: 'train-001',
    employeeId: 'user-008',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-06-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-15'),
    score: 97,
    attempts: 1,
  },
  {
    id: 'assign-025',
    trainingId: 'train-004',
    employeeId: 'user-008',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-05-01'),
    dueDate: new Date('2024-06-01'),
    completedDate: new Date('2024-05-18'),
    score: 94,
    attempts: 1,
  },
  {
    id: 'assign-026',
    trainingId: 'train-003',
    employeeId: 'user-008',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-07-01'),
    dueDate: new Date('2024-08-01'),
    completedDate: new Date('2024-07-20'),
    score: 89,
    attempts: 1,
  },
  {
    id: 'assign-027',
    trainingId: 'train-009',
    employeeId: 'user-008',
    assignedById: 'user-002',
    status: 'in-progress',
    assignedDate: new Date('2024-09-15'),
    dueDate: new Date('2024-11-15'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-028',
    trainingId: 'train-007',
    employeeId: 'user-008',
    assignedById: 'user-001',
    status: 'not-started',
    assignedDate: new Date('2024-10-01'),
    dueDate: new Date('2024-12-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // David Lee (user-009) - Finance - 4 assignments
  {
    id: 'assign-029',
    trainingId: 'train-001',
    employeeId: 'user-009',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-06-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-30'),
    score: 82,
    attempts: 2,
  },
  {
    id: 'assign-030',
    trainingId: 'train-003',
    employeeId: 'user-009',
    assignedById: 'user-001',
    status: 'overdue',
    assignedDate: new Date('2024-08-01'),
    dueDate: new Date('2024-09-01'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-031',
    trainingId: 'train-005',
    employeeId: 'user-009',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-04-01'),
    dueDate: new Date('2024-05-01'),
    completedDate: new Date('2024-04-25'),
    score: 84,
    attempts: 1,
  },
  {
    id: 'assign-032',
    trainingId: 'train-010',
    employeeId: 'user-009',
    assignedById: 'user-001',
    status: 'in-progress',
    assignedDate: new Date('2024-09-20'),
    dueDate: new Date('2024-11-20'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // Lisa Anderson (user-010) - Engineering - 5 assignments
  {
    id: 'assign-033',
    trainingId: 'train-001',
    employeeId: 'user-010',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-06-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-22'),
    score: 88,
    attempts: 1,
  },
  {
    id: 'assign-034',
    trainingId: 'train-003',
    employeeId: 'user-010',
    assignedById: 'user-001',
    status: 'expired',
    assignedDate: new Date('2024-02-15'),
    dueDate: new Date('2024-03-15'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-035',
    trainingId: 'train-006',
    employeeId: 'user-010',
    assignedById: 'user-001',
    status: 'completed',
    assignedDate: new Date('2024-05-01'),
    dueDate: new Date('2024-07-01'),
    completedDate: new Date('2024-06-28'),
    score: 74,
    attempts: 2,
  },
  {
    id: 'assign-036',
    trainingId: 'train-008',
    employeeId: 'user-010',
    assignedById: 'user-001',
    status: 'not-started',
    assignedDate: new Date('2024-10-01'),
    dueDate: new Date('2024-12-31'),
    completedDate: null,
    score: null,
    attempts: 0,
  },
  {
    id: 'assign-037',
    trainingId: 'train-002',
    employeeId: 'user-010',
    assignedById: 'user-002',
    status: 'overdue',
    assignedDate: new Date('2024-07-15'),
    dueDate: new Date('2024-08-15'),
    completedDate: null,
    score: null,
    attempts: 0,
  },

  // Extra assignments for more coverage
  {
    id: 'assign-038',
    trainingId: 'train-002',
    employeeId: 'user-003',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-04-15'),
    dueDate: new Date('2024-05-15'),
    completedDate: new Date('2024-05-10'),
    score: 78,
    attempts: 1,
  },
  {
    id: 'assign-039',
    trainingId: 'train-005',
    employeeId: 'user-007',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-03-15'),
    dueDate: new Date('2024-04-15'),
    completedDate: new Date('2024-04-10'),
    score: 83,
    attempts: 1,
  },
  {
    id: 'assign-040',
    trainingId: 'train-009',
    employeeId: 'user-009',
    assignedById: 'user-002',
    status: 'completed',
    assignedDate: new Date('2024-04-01'),
    dueDate: new Date('2024-05-01'),
    completedDate: new Date('2024-04-28'),
    score: 79,
    attempts: 1,
  },
];

export const MOCK_PASSWORDS: Map<string, string> = new Map([
  ['admin@company.com', 'admin123'],
  ['sarah.admin@company.com', 'admin123'],
  ['john@company.com', 'employee123'],
  ['jane@company.com', 'employee123'],
  ['bob@company.com', 'employee123'],
  ['alice@company.com', 'employee123'],
  ['mike@company.com', 'employee123'],
  ['emma@company.com', 'employee123'],
  ['david@company.com', 'employee123'],
  ['lisa@company.com', 'employee123'],
]);
